apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service_name }}
spec:
  selector:
    app: {{ .Values.deployment_name }}
  type:  {{ .Values.service_type }}
  ports:
  - name: port-80
    protocol: TCP
    port: 80
    targetPort: {{ .Values.image.port }}